# Generated by Django 4.2.30 on 2026-08-10 15:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0015_player_location'),
        ('content', '0001_initial'),
        ('locations', '0001_initial'),
        ('groups', '0003_group_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('last_deploy_status', models.JSONField(blank=True, default=dict, help_text='Per-player result of the last deploy, e.g. {player_id: {name, success, items}}.')),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_groups', models.ManyToManyField(blank=True, related_name='playlists', to='groups.group')),
                ('target_locations', models.ManyToManyField(blank=True, related_name='playlists', to='locations.location')),
                ('target_players', models.ManyToManyField(blank=True, related_name='playlists', to='players.player')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('duration', models.IntegerField(blank=True, help_text='Duration override in seconds. Leave empty to use the default.', null=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='content.mediafile')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
