# Generated by Django 4.2.30 on 2026-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='deployed_assets',
            field=models.JSONField(blank=True, default=dict, help_text='Per-player asset IDs created by the last deploy, e.g. {player_id: [asset_id, ...]}. Removed before redeploying so re-applying a playlist does not duplicate its content.'),
        ),
    ]
