# Generated by Django 4.2.30 on 2026-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0005_mfaproviderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacyideaenrollment',
            name='token_type',
            field=models.CharField(choices=[('totp', 'totp'), ('push', 'push')], default='totp', max_length=8),
        ),
    ]
