# Generated by Django 4.2.30 on 2026-08-15 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mfa', '0006_privacyideaenrollment_token_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_dual_roles', models.JSONField(default=list, help_text="Subset of ['viewer', 'editor', 'admin', 'superadmin'] that must always pass two MFA challenges to log in.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
