# Generated by Django 4.2.30 on 2026-08-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('groups', '0002_alter_group_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='locations.location'),
        ),
    ]
