# Generated by Django 4.2.30 on 2026-08-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='splash_logo',
            field=models.FileField(blank=True, help_text='Overrides the fleet-wide splash logo for devices in this group.', null=True, upload_to='branding/groups/'),
        ),
        migrations.AddField(
            model_name='group',
            name='standby_image',
            field=models.FileField(blank=True, help_text='Overrides the fleet-wide standby image for devices in this group.', null=True, upload_to='branding/groups/'),
        ),
    ]
