# Generated by Django 4.2.30 on 2026-08-10 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0015_player_location'),
        ('groups', '0003_group_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(blank=True, related_name='scoped_users', to='groups.group')),
                ('locations', models.ManyToManyField(blank=True, related_name='scoped_users', to='locations.location')),
                ('players', models.ManyToManyField(blank=True, related_name='scoped_users', to='players.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_scope', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
