# Generated by Django 4.2.30 on 2026-08-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_useraccessscope_can_delete_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccessscope',
            name='force_mfa_enroll',
            field=models.BooleanField(default=False, help_text='Set at user creation to force MFA enrolment (TOTP or Duo) before the user can use the Fleet Manager. Cleared automatically once either enrolment is confirmed.'),
        ),
        migrations.AddField(
            model_name='useraccessscope',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set at user creation to force a password change before the user can use the Fleet Manager. Cleared automatically once they change it via the self-service change-password endpoint.'),
        ),
    ]
