# Generated by Django 4.2.30 on 2026-08-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_useraccessscope_force_mfa_enroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccessscope',
            name='require_dual_mfa',
            field=models.BooleanField(default=False, help_text="Self-service opt-in: require two challenges from two different MFA providers to log in, not just one. Independent of (and additive to) mfa.models.MFAPolicy's admin-set per-role requirement — either one being true is enough to trigger it. Only takes effect once this user has 2+ confirmed providers enrolled; with just one, login degrades to that single factor rather than locking them out. See mfa/policy.py::dual_mfa_required, the only reader."),
        ),
    ]
