# Generated by Django 4.2.30 on 2026-08-17 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_splash_logo_group_standby_image'),
        ('locations', '0002_location_splash_logo_location_standby_image'),
        ('content', '0005_scheduleddeployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafolder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_folders', to='groups.group'),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='is_common',
            field=models.BooleanField(default=False, help_text='Visible to every editor regardless of their own location/group scope — set from Settings > Content Library, not directly editable here.'),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_folders', to='locations.location'),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='content.mediafolder'),
        ),
    ]
