# Generated by Django 4.2.30 on 2026-08-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='splash_logo',
            field=models.FileField(blank=True, help_text='Overrides the fleet-wide (and group) splash logo for devices in this location.', null=True, upload_to='branding/locations/'),
        ),
        migrations.AddField(
            model_name='location',
            name='standby_image',
            field=models.FileField(blank=True, help_text='Overrides the fleet-wide (and group) standby image for devices in this location.', null=True, upload_to='branding/locations/'),
        ),
    ]
