# Generated by Django 4.2.30 on 2026-08-18 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_location_splash_logo_location_standby_image'),
        ('groups', '0004_group_splash_logo_group_standby_image'),
        ('players', '0031_alter_provisiontask_total_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_groups', models.ManyToManyField(blank=True, related_name='footer_messages', to='groups.group')),
                ('target_locations', models.ManyToManyField(blank=True, related_name='footer_messages', to='locations.location')),
                ('target_players', models.ManyToManyField(blank=True, related_name='footer_messages', to='players.player')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
