# Generated by Django 4.2.30 on 2026-08-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('players', '0014_move_playbacklog_to_history_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Only used when the player has no group — a group's own location takes precedence.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='locations.location'),
        ),
    ]
