# Generated by Django 4.2.30 on 2026-08-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_player_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='splash_logo',
            field=models.FileField(blank=True, help_text='Overrides the group/location/fleet-wide splash logo for this device only.', null=True, upload_to='branding/players/'),
        ),
        migrations.AddField(
            model_name='player',
            name='standby_image',
            field=models.FileField(blank=True, help_text='Overrides the group/location/fleet-wide standby image for this device only.', null=True, upload_to='branding/players/'),
        ),
    ]
