# Generated by Django 4.2.30 on 2026-08-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_player_sso_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='device_type',
            field=models.CharField(blank=True, choices=[('pi4', 'Raspberry Pi 4'), ('pi5', 'Raspberry Pi 5'), ('x86', 'x86'), ('unknown', 'Unknown')], default='unknown', help_text='Detected hardware type (pi4, pi5, x86).', max_length=10),
        ),
        migrations.AlterField(
            model_name='provisiontask',
            name='total_steps',
            field=models.IntegerField(default=12),
        ),
    ]
