# Generated by Django 4.2.30 on 2026-08-16 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0029_alter_player_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPairing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poll_token', models.CharField(max_length=64)),
                ('pairing_code', models.CharField(max_length=12)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_requests', to='players.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
