# Generated by Django 4.2.30 on 2026-08-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_pendingpairing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisiontask',
            name='total_steps',
            field=models.IntegerField(default=14),
        ),
    ]
